server:
  port: 12005

# 解决跨域问题，在ES的elasticsearch.yml中最后两行
http.cors.enabled: true
http.cors.allow-origin: "*"
spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200

rocketmq:
  consumer:
    isOnOff: on
    # 官方建议：确保同一组中的每个消费者订阅相同的主题。
    groupName: ${spring.application.name}
    namesrvAddr: 127.0.0.1:9876
    # 接收该 Topic 下所有 Tag
    topics: user_server_topic~*;test_topic~*;
    consumeThreadMin: 20
    consumeThreadMax: 64
    # 设置一次消费消息的条数，默认为1条
    consumeMessageBatchMaxSize: 1